Fix the configure command. (#362)
I tried walking through the self hosting instructions, but ran into a bug. The
executor wouldn't start because of an error at at startup:

```
error: getting storage path: $HOME is not defined
```

That error originates from [this code](https://github.com/allenai/beaker-service/blob/5a9afb877321519943eb2f2d1446b9f4c367c1a8/cmd/executor/main.go#L122-L125),
which is executed as the executor starts up.

The error occurs because we try to use the process owner's [home directory](https://github.com/allenai/beaker-service/blob/5a9afb877321519943eb2f2d1446b9f4c367c1a8/cmd/executor/main.go#L48)
as a default, but because the process is ran non-interactively, `$HOME` isn't set.

This fixes that by explicitly setting the storage path to `/var/beaker`, and
by making sure that directory exists.

Alternatively we could change the default, though that'll require updating that
default in multiple places. As we currently resolve the default in both
the executor and the CLI.